# Generated by Django 4.2 on 2023-04-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oreder',
            name='status',
        ),
        migrations.AddField(
            model_name='order_item',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
