# Generated by Django 4.1.1 on 2023-04-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_oreder_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oreder',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
