# Generated by Django 4.1.1 on 2023-03-10 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hcart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_details', models.CharField(max_length=500)),
                ('product_number', models.BigIntegerField()),
                ('current_stock', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product')),
                ('product_price', models.FloatField()),
                ('product_category', models.CharField(default='', max_length=100)),
                ('product_place', models.CharField(default='', max_length=100)),
                ('seller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hcart.seller')),
            ],
        ),
    ]
